---

- name: Create Ping Template Job
  tower_job_template:
    name: "Ping Test Instances"
    job_type: "run"
    inventory: "aws-inventory"
    project: "test instances"
    playbook: "ping-test-ec2.yaml"
    credential: "Machine SSH"
    state: "present"
    tower_config_file: ../../../tower_cli.cfg
