---

### Create credentials
- name: Create Source Control Credential
  tower_credential:
    name: "Source Control - liveproject"
    description: github credential
    organization: 'Unicorn Bank Corp.'
    kind: scm
    username: git@github.com
    ssh_key_data: "{{ ssh_key }}"
    ssh_key_unlock: "{{ ssh_key_password }}"

- name: Create Machine SSH Credential
  tower_credential:
    name: "Machine SSH"
    description: Remote Machine SSH Credential
    organization: 'Unicorn Bank Corp.'
    kind: ssh
    state: present
    ssh_key_data: "{{ ssh_key }}"
    ssh_key_unlock: "{{ ssh_key_password }}"
    become_method: sudo
    username: ec2-user

- name: Create AWS API Credential
  tower_credential:
    name: "AWS Acc. 722269482003"
    kind: aws
    organization: 'Unicorn Bank Corp.'
    # AWS Access Key
    username: "{{ aws_access_key }}"
    # AWS Secret Key
    password: "{{ aws_secret_key }}"
    state: present

### Create Templates
- name: Create Ping Template Job
  tower_job_template:
    name: "Ping Test Instances"
    job_type: "run"
    inventory: "aws-inventory"
    project: "test instances"
    playbook: "ping-test-ec2.yaml"
    credential: "Machine SSH"
    state: "present"
    tower_config_file: ~/tower_cli.cfg

- name: Create Create Test Instances Job
  tower_job_template:
    name: "Create Test Instances"
    job_type: "run"
    inventory: "AWS API"
    project: "test instances"
    playbook: "create-test-ec2.yaml"
    credential: "AWS Acc. 722269482003"
    state: "present"
    tower_config_file: ~/tower_cli.cfg

- name: Create Destroy Test Instances Job
  tower_job_template:
    name: "Destroy Test Instances"
    job_type: "run"
    inventory: "AWS API"
    project: "test instances"
    playbook: "destroy-test-ec2.yaml"
    credential: "AWS Acc. 722269482003"
    state: "present"
    tower_config_file: ~/tower_cli.cfg
